### ISSUE TITLE
Detecting RaptorShock

### ISSUE THREAD

**Issue by Marcus101RR** [ivanbiljan/ZmajShock#1]
My analysis is complete, the reason why this plugin can't find the instance of raptor shock hangs in the fact that the instance is located in plugins/RaptorShock.dll, but when you start Raptor, the error reports that it cannot find this plugin, because it requests RaptorShock.dll to be placed in the root directory of Raptor itself. This is where the problem lies. The instance of the DLL is in plugins/RaptorShock.dll, but the reference it wants is located in the main folder instead. Hence you have no instance of this plugin.

Most like this can only be solved within raptor itself?

**Comment by ProfessorXZ** [comment]
Yes, I am aware. And yes, it can only be solved within Raptor. That's why I did [this](https://github.com/ProfessorXZ/Raptor/commit/0cc486793b782e614086b3632dc28de24b4d348e). Everything seems to work as intended after applying the fix.
